# Generated by Django 2.1.7 on 2019-02-11 19:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('twitter_id', models.IntegerField(verbose_name='twitter id')),
                ('twitter_handle', models.CharField(max_length=256, verbose_name='twitter handle')),
                ('followers_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None, verbose_name='followers ids')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
