# Generated by Django 2.1.7 on 2019-02-17 13:00

import django.contrib.postgres.fields
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecondLineFollowersCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                (
                'screen_name', models.CharField(max_length=256, null=True, unique=True, verbose_name='twitter handle')),
                ('user_id', models.BigIntegerField(null=True, unique=True, verbose_name='twitter id')),
                ('followers', django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='followers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                (
                'screen_name', models.CharField(max_length=256, null=True, unique=True, verbose_name='twitter handle')),
                ('user_id', models.BigIntegerField(null=True, unique=True, verbose_name='twitter id')),
                ('followers_ids',
                 django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), null=True, size=None,
                                                           verbose_name='followers ids')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
